### ISSUE TITLE
LSF Array Jobs Missing

### ISSUE THREAD

**Issue by jakirkham** [krokicki/derecho#1]
I'm seeing in Derecho that I have 2 jobs running (both are on LSF). However I have 32 jobs running actually. Initially I thought this might be a lag issue. However I started up these jobs around 1:02p, but it has been over 45mins and the problem persists. FWIW the 28 jobs that are missing appear to be those that are part of a job array. More details below.

LSF command line:

<details>

```
[login1 - kirkhamj@c11u24]~/Wanchen2John_new>bjobs -X
JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
657553  kirkham RUN   normal     c11u24      h06u25      *10.106698 Jul 12 11:56
661431  kirkham RUN   normal     h06u25      h06u18      *ontroller Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u18      *engine[1] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[2] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[3] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[4] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[5] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[6] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[7] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[8] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *engine[9] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[10] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[11] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[12] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[13] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[14] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[15] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[16] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u12      *ngine[17] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[18] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[19] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[20] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[21] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[22] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[23] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[24] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[25] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[26] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[27] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[28] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[29] Jul 12 13:02
661442  kirkham RUN   normal     h06u25      h06u04      *ngine[30] Jul 12 13:02

```

</details>

<br>
Derecho Web:
<br>
<br>

<details>

<img width="1552" alt="screen shot 2017-07-12 at 13 49 01" src="https://user-images.githubusercontent.com/3019665/28148637-050cc550-6756-11e7-9cbf-583ed6f01b92.png">

</details>

**Comment by krokicki** [comment]
Thanks! I'm still figuring out the parsing for LSF. Yesterday I rewrote the entire parser using bjobs -o instead of bjobs -UF, so it should be a lot more reliable now. I'll be ironing out issues for the next few weeks, but if you see something strange after that, please let me know.

**Comment by jakirkham** [comment]
> I'm still figuring out the parsing for LSF.

Aren't we all. :)

> Yesterday I rewrote the entire parser using bjobs -o instead of bjobs -UF, so it should be a lot more reliable now.

That seems like a good idea. I do recall using some `bjobs` options would result in non-running jobs being returned as well. So something to watch out for.

> I'll be ironing out issues for the next few weeks, but if you see something strange after that, please let me know.

I saw some issue yesterday where it showed way more jobs were running than expected. Not sure if this was before or after the change. Will open a new issue if I see it again.

**Comment by krokicki** [comment]
I actually know about that one. Whenever the number of slots is unknown it uses 9999, which results in those huge numbers. I just need to hunt down all the cases where number of slots is not being reported as max_req_proc, and use some other field as a fallback.

**Comment by krokicki** [comment]
I solved it by defaulting to max_req_proc, and replacing that with nalloc_slot if it's available. 

I think it should be reasonably reliable at this point. Please let me know if you see any more inconsistencies.
